algoritmo "mediaaluno"
var
nota1: real
nota2: real
nota3: real
media: real

inicio
Escreva ("Informe a nota da primeira prova feita pelo aluno: ")
Leia (nota1)
Escreva ("Informe a nota da segunda prova feita pelo aluno: ")
Leia (nota2)
Escreva ("Informe a nota da terceira prove realizada pelo aluno: ")
Leia (nota3)
media <- (nota1+nota2+nota3)/3
Escreva ("Com base nas seguintes notas:",nota1,",",nota2,",",nota3,",a média do aluno será a seguinte: ",media)
fimalgoritmo